version: '3.8'

services:
  fishsnap-backend-ts-dev:
      container_name: fishsnap-backend-ts-dev
      build:
        context: ./
        dockerfile: ./Dockerfile
      command: ["sh", "-c", "chmod +x ./entrypoint.sh && ./entrypoint.sh"]
      ports:
        - ${PORT_BE}:${PORT_DEFAULT_3000}
      environment:
        DATABASE_URL: ${DATABASE_URL_LOCAL}
        BASE_URL: ${BASE_URL}
        BASE_URL_STORAGE_BUCKET: ${BASE_URL_STORAGE_BUCKET_DEV}
      volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
      depends_on:
        - postgres_fishsnap
      restart: unless-stopped

  postgres_fishsnap:
    container_name: fishsnap_postgres_db_dev
    image: postgres:14
    ports:
      - ${PORT_DB}:${PORT_DEFAULT_5432}
    environment:
      POSTGRES_USER: ${POSTGRES_USER_DEV}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
      POSTGRES_DB: ${POSTGRES_DB_DEV}
    volumes:
      - 'data-postgres-development:/var/lib/postgresql/data'

volumes:
  data-postgres-development:
    name: data-postgres-development
  data-postgres-development-migrate:
    name: data-postgres-development-migrate

networks:
  default:
    name: fishsnap-network-dev
    external: true
